### ISSUE TITLE
Memory error when run_psa() and run_dsa()

### ISSUE THREAD

**Issue by TwT9807** [cran/heemod#1]
When running the run_dsa and run_psa, the program takes up too much memory, and I always run into problems like "cannot allocate vector of size ***". I have tried gc() before run_dsa and run_psa, and I have tried to run them on fewer cores, but the problem still persists. Maybe it is the complexity of the Markov model (5 states) that generates the problems, but I cannot make the model simpler. Anyway, I love the heemod package, but is there any method that I can use to reduce memory usage and prevent such errors?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by TwT9807** [comment]
Oh. Thanks.
